import os

SERVICE_NAME = "identity-service"
APP_VERSION = os.getenv("APP_VERSION", "0.1.0")
MAX_DID_DOCUMENT_BYTES = int(os.getenv("MAX_DID_DOCUMENT_BYTES", "16384"))
MAX_CREDENTIAL_BYTES = int(os.getenv("MAX_CREDENTIAL_BYTES", "32768"))
MAX_CREDENTIAL_REQUEST_BYTES = int(
    os.getenv("MAX_CREDENTIAL_REQUEST_BYTES", "36864")
)
MAX_AUTH_REQUEST_BYTES = int(os.getenv("MAX_AUTH_REQUEST_BYTES", "4096"))
MAX_REVOCATION_REQUEST_BYTES = int(
    os.getenv("MAX_REVOCATION_REQUEST_BYTES", "4096")
)
MAX_PRESENTATION_REQUEST_BYTES = int(
    os.getenv("MAX_PRESENTATION_REQUEST_BYTES", "69632")
)
MAX_JSON_DEPTH = int(os.getenv("MAX_JSON_DEPTH", "32"))
DID_NETWORK_RESOLUTION_ENABLED = (
    os.getenv("DID_NETWORK_RESOLUTION_ENABLED", "false").lower() == "true"
)
